const userdata = {
    "login":"zenx5",
    "id":26119733,
    "node_id":"MDQ6VXNlcjI2MTE5NzMz",
    "avatar_url":"https://avatars.githubusercontent.com/u/26119733?v=4",
    "gravatar_id":"",
    "url":"https://api.github.com/users/zenx5",
    "html_url":"https://github.com/zenx5",
    "followers_url":"https://api.github.com/users/zenx5/followers",
    "following_url":"https://api.github.com/users/zenx5/following{/other_user}",
    "gists_url":"https://api.github.com/users/zenx5/gists{/gist_id}",
    "starred_url":"https://api.github.com/users/zenx5/starred{/owner}{/repo}",
    "subscriptions_url":"https://api.github.com/users/zenx5/subscriptions",
    "organizations_url":"https://api.github.com/users/zenx5/orgs",
    "repos_url":"https://api.github.com/users/zenx5/repos",
    "events_url":"https://api.github.com/users/zenx5/events{/privacy}",
    "received_events_url":"https://api.github.com/users/zenx5/received_events",
    "type":"User",
    "site_admin":false,
    "name":"Octavio Martinez",
    "company":null,
    "blog":"",
    "location":"Venezuela - Puerto Ordaz",
    "email":"omartinez1618@gmail.com",
    "hireable":null,
    "bio":"Self Taught, passionate and a dreamer. Programming is my thing. Pascal at 12, Javascript from a Nokia 6262, PHP by chance... I enjoy challenging myself and push",
    "twitter_username":null,
    "public_repos":112,
    "public_gists":0,
    "followers":6,
    "following":11,
    "created_at":"2017-03-01T16:29:45Z",
    "updated_at":"2023-09-25T23:13:49Z"
}

export default userdata